language: php
sudo: false

php:
  - 5.5

before_install:
  - mysql -e "create database IF NOT EXISTS csr;" -uroot

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  # -------------- move to make command -----
  - git clone https://github.com/TransformCore/CSR-Fast-Stream-backend.git
  - cp composer.phar CSR-Fast-Stream-backend/
  - cd CSR-Fast-Stream-backend/
  - git checkout develop
  - php composer.phar install --dev --no-interaction
  - make symfony.server &
  - cd ..
  # -----------------------------------------
  - make symfony.dev.rebuild

script:
  - make symfony.test.bdd suite=transformcore_app config=test/behat.yml
#  - make symfony.test.spec config=test/phpspec.yml
  - make scrutinizer.coverage

after_success:
  - make build.package

after_failure:
  - make symfony.logs

branches:
  except:
    - /^build-[0-9a-z\-\/]*/

services:
  - mysql

notifications:
  slack:
    secure: vYPx6okG78QdCRsV+9cCPPC+URz7vtBjm0ID/7t0L0Ef9wJ5Wl/eln97rPRNiRUWRGGu8mwdQFh7JQCEqZQftYAkTx8PlV7VlLToai4rEHEupE0/KVdors70DXvlovznUQYVhVmQBgWKXrkWNgGFLqzH1Z8qXykrL/pNvVqTZyM=

env:
  global:
    - secure: U1TFca6LeHYWKiBJznqjO7c8F8sK63OnH37O/v+9N/wvp9YBusDzJ0NyerFbxce4c28ZL1JFUQUgAqeHOzDFjHdqY7sHD8YHSUEZS9ZCjXsfnKnEIPY/HOCOOED7dYZrLp6NZFF1B3BoosguFTenEMT2XEc1DsmwfHk3aqLYNes=
    - SYMFONY__DATABASE__HOST="127.0.0.1"
    - SYMFONY__DATABASE__NAME="csr"
    - SYMFONY__DATABASE__USER="root"
    - SYMFONY__DATABASE__PASSWORD=""

deploy:
  provider: heroku
  api_key:
    secure: ioz9Hi/hAbvd+1VuiH3aQwRpyjMP0OvkhafMyMcksK8tQjd5j8r8MeRILza3BO2XvVKGHjUJuCLoYnGt84+m7npNP7OeiSavJQL40CN/VMTmDyEpRVoyMNqkPxjuFQCuHsx1d/uN1ADkx61HaP6LCglrA1mSmcHWwGiVwg8OnQc=
  app: csr-frontend-ci
  on:
    all_branches: true
  run:
      - "make symfony.dev.rebuild"
