transform_core_app_changelog:
    path:     /changelog
    defaults: { _controller: TransformCoreAppBundle:Default:changelog }

transform_core_app_homepage:
    path:     /
    defaults: { _controller: TransformCoreAppBundle:Default:index }

transform_core_app_account:
    path:     /account
    defaults: { _controller: TransformCoreAppBundle:Default:account }
