transform_core_app_changelog:
    path:     /changelog
    defaults: { _controller: TransformCoreAppBundle:Default:changelog }

transform_core_app_homepage:
    path:     /
    defaults: { _controller: TransformCoreAppBundle:Default:index }

transform_core_app_user:
    path:     /user
    defaults: { _controller: TransformCoreAppBundle:User:index }