transform_core_app_changelog:
    path:     /changelog
    defaults: { _controller: TransformCoreAppBundle:Default:changelog }

transform_core_app_homepage:
    path:     /
    defaults: { _controller: TransformCoreAppBundle:Default:index }


transform_core_app_mycall:
    path:    /testcall
    defaults: { _controller: TransformCoreAppBundle:MyCall:index }


