services:
#    transform_core_app.example:
#        class: TransformCore\Bundle\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  transform_core_app_main.menu_builder:
    class: TransformCore\Bundle\AppBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory","@security.context"]

  transform_core_app_main.menu.main:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory_service: transform_core_app_main.menu_builder
    factory_method: createMainMenu
    arguments: ["@request"]
    scope: request # needed as we have the request as a dependency here
    tags:
        - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

  transform_core_app_main.service.version:
    class: TransformCore\Bundle\AppBundle\Service\Version
    arguments: ["%kernel.root_dir%/../version"]

  transform_core_app_main.service.random_username_generator:
    class: TransformCore\Bundle\AppBundle\Service\RandomUsernameGenerator

  transform_core_app_user_registration_listener:
    class: TransformCore\Bundle\AppBundle\EventListener\RegistrationListener
    arguments: [@router, @transform_core_app_main.service.random_username_generator]
    tags:
        - { name: kernel.event_subscriber }

  transform_core_app_main.service.applicants:
    class: TransformCore\Bundle\AppBundle\Service\Applicants
    arguments: [@transform_core_app_main.service.http, @jms_serializer]

  transform_core_app_main.service.eligibility:
    class: TransformCore\Bundle\AppBundle\Service\Eligibility
    arguments: [@transform_core_app_main.service.http, @jms_serializer]

  transform_core_app_main.service.http:
    class: GuzzleHttp\Client
    arguments: [%api_url%]
