services:
#    transform_core_app.example:
#        class: TransformCore\Bundle\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  transform_core_app_main.menu_builder:
    class: TransformCore\Bundle\AppBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

  transform_core_app_main.menu.main:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory_service: transform_core_app_main.menu_builder
    factory_method: createMainMenu
    arguments: ["@request"]
    scope: request # needed as we have the request as a dependency here
    tags:
        - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

  transform_core_app_main.service.version:
      class: TransformCore\Bundle\AppBundle\Service\Version
      arguments: ["%kernel.root_dir%/../version"]
      
  myForm.form.flow.myForm.Storage:
      class: TransformCore\Bundle\AppBundle\Form\MyStorage
      scope: request
      arguments:
        - "@session"
      calls:
        - [ setLogger, [ @logger ] ]
  
  myForm.form.flow.myForm:
      class: TransformCore\Bundle\AppBundle\Form\MyFormFlow
      parent: craue.form.flow
      scope: request
      calls:
        - [ setStorage, [ "@myForm.form.flow.myForm.Storage" ] ]