transform_core_user:
    resource: "@TransformCoreUserBundle/Resources/config/routing.yml"
    prefix:   /

transform_core_app:
    resource: "@TransformCoreAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
