TransformCore\Bundle\CsrFastStreamBundle\Entity\Applicant:
    exclusion_policy: all
    properties:
        id:
            expose: true
            type: integer
        firstname:
            expose: true
        lastname:
            expose: true
        phoneNumber:
            expose: true
        dateOfBirth:
            expose: true
            type: DateTime<'Y-m-d'>
        address:
            expose: true
