FOS\UserBundle\Model\User:
    exclusion_policy: all
    properties:
        email:
            expose: true
        plainPassword:
            expose: true
        enabled:
            expose: false
        id:
            expose: true
            type: integer
        username:
            expose: false
